services:
  web:
    build: .
    ports:
      - "4321:4321"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm ci || npm i && npm run dev -- --host 0.0.0.0 --port 4321"

volumes:
  node_modules:
